<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TicketSeeder extends Seeder
{
    public function run()
    {
        DB::table('tickets')->insert([
            [
                'title' => 'Masalah Login',
                'description' => 'Tidak bisa login ke sistem',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Error pada Halaman Dashboard',
                'description' => 'Dashboard tidak menampilkan data dengan benar',
                'priority' => 'medium', 
                'status' => 'in_progress',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Permintaan Fitur Baru',
                'description' => 'Mohon tambahkan fitur export ke Excel',
                'priority' => 'low',
                'status' => 'open',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bug pada Form Input',
                'description' => 'Validasi form tidak berfungsi',
                'priority' => 'high',
                'status' => 'closed',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Optimasi Database',
                'description' => 'Query terlalu lambat saat load data',
                'priority' => 'medium',
                'status' => 'open',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Update UI/UX',
                'description' => 'Tampilan perlu diperbaharui sesuai design terbaru',
                'priority' => 'low',
                'status' => 'in_progress',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Integrasi Payment Gateway',
                'description' => 'Implementasi pembayaran online',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Error 404',
                'description' => 'Beberapa halaman menampilkan 404',
                'priority' => 'medium',
                'status' => 'closed',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Backup System',
                'description' => 'Implementasi automatic backup',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Email Notification',
                'description' => 'Setup email notification system',
                'priority' => 'medium',
                'status' => 'in_progress',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Security Update',
                'description' => 'Pembaruan keamanan sistem',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mobile Responsive',
                'description' => 'Perbaikan tampilan mobile',
                'priority' => 'medium',
                'status' => 'closed',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'API Integration',
                'description' => 'Integrasi dengan third party API',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Performance Issue',
                'description' => 'Optimasi kinerja aplikasi',
                'priority' => 'high',
                'status' => 'in_progress',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Data Migration',
                'description' => 'Migrasi data dari sistem lama',
                'priority' => 'medium',
                'status' => 'open',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Server Maintenance',
                'description' => 'Jadwal maintenance server',
                'priority' => 'low',
                'status' => 'closed',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bug Report',
                'description' => 'Laporan bug pada modul laporan',
                'priority' => 'high',
                'status' => 'open',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Feature Request',
                'description' => 'Permintaan penambahan fitur baru',
                'priority' => 'low',
                'status' => 'in_progress',
                'created_by' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Database Backup',
                'description' => 'Backup database mingguan',
                'priority' => 'medium',
                'status' => 'open',
                'created_by' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SSL Certificate',
                'description' => 'Pembaruan SSL Certificate',
                'priority' => 'high',
                'status' => 'closed',
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}